- name: Install and Configure Nginx
  hosts: webservers
  become: yes 

  tasks:
    - name: Install Required Packages
      apt:
        name: 
          - nginx
          - git
          - ufw
        state: present
        update_cache: yes

    - name: Start and enable Nginx
      service: 
        name: nginx
        state: started
        enabled: yes

    - name: Allow HTTP and SSH trough the firewall
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - 22
        - 80

    - name: Clone website repository
      become_user: www-data
      git:
        repo: "https://github.com/scm-ninja/starter-web.git"
        dest: "/var/www/html/my_website"
        force: yes

    - name: Set permissions
      file:
        path: "/var/www/html/my_website"
        owner: "www-data"
        group: "www-data"
        recurse: yes

    - name: Nginx configuration
      copy:
        dest: "/etc/nginx/sites-available/default"
        content: |
          server {
            listen 80;
            server_name _;
            root /var/www/html/my_website;
            index index.html index.html;

            location / {
              try_files $uri $uri/ =404;
            }
          }
      notify:
        - Restart Nginx

  handlers:    
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
 
